# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true
test: off # this turns of AppVeyor automatic searching for test-assemblies, not the actual testing
build_script:
  - ps: .\build.ps1 All -publish-all -archive
artifacts:
  - path: artifacts/package/*.zip
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: YW4vAIFrVIdyKBNxyVGWGKHP2UejoZcTcD0cf7KYEgZefUWY2XFHjetDW4Q0cICx
    artifact: /.*\.zip/
    on:
      appveyor_repo_tag: true
notifications:
  - provider: Slack
    auth_token:
      secure: OU7mWtP+JWLRV2Ofq3/QMQbudeN632xLgWb4zMJtOssi2v5HER4qe0GFoj/rnIYOBXd3d/5+glfKG3ijvCU3bA==
    channel: '#integrations'
environment:
  BLOB_STORAGE_CONNECTION_STRING:
    secure: ljYC4LQpALoXTXY+cwRgb2VpVrQvVR/dhHZdSR+3l3aljOXzisHd/E1gjwPiD1MjXqhjrct1UWjKu0pIb738gjnH5VayJfTpZ575hNwoM1DFAOjuxaBhAOmJyVdOTy0tHp3tMHqzd53wkD0VXDlbW9rg1FvG9/CmJRXCOVDJV8WSnr/Whjmm8KF90h/F6MP6FwHjWbZnITKjwLEGOKHVgcTFh1Fr1fQLynmQb4MbCxKtGYSq2jX2INxU9tas3Qmn
